version: '3'

services:

  mlflowui:
    build: ./mlflowUI/.
    restart: always
    volumes: ['./storage/mlflow:/tmp/mlflowruns'] 
    networks:
        - jupyter
    expose:
        - "5000"
    ports:
        - "5000:5000"
    environment: 
      - LC_ALL=C.UTF-8 
      - LANG=C.UTF-8

  elyra:
    image: elyra/elyra:dev
    restart: always
    command: ["jupyter", "lab", "--debug"]
    volumes: ['./storage/jupyter:/home/jovyan/work']
    networks:
      - jupyter
    expose:
      - "8888" 
    ports:
      - "8888:8888"
    #environment:
    #privileged: true

networks:
  jupyter: