artifact_uri: /tmp/mlflowruns/0/cb950a12b06249cdbdeb91c2db521e19/artifacts
end_time: 1607021154586
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: cb950a12b06249cdbdeb91c2db521e19
run_uuid: cb950a12b06249cdbdeb91c2db521e19
source_name: ''
source_type: 4
source_version: ''
start_time: 1607021154349
status: 3
tags: []
user_id: jovyan
