artifact_uri: s3://mlflowruns/4/1d8e14a94a1e4e3aa382df33beb0a1a9/artifacts
end_time: 1607022972170
entry_point_name: ''
experiment_id: '4'
lifecycle_stage: active
name: ''
run_id: 1d8e14a94a1e4e3aa382df33beb0a1a9
run_uuid: 1d8e14a94a1e4e3aa382df33beb0a1a9
source_name: ''
source_type: 4
source_version: ''
start_time: 1607022971926
status: 4
tags: []
user_id: jovyan
