artifact_uri: s3://mlflowruns/2/457a7c412bbf49e6b14ad3a2f4db38f9/artifacts
end_time: 1607022450102
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 457a7c412bbf49e6b14ad3a2f4db38f9
run_uuid: 457a7c412bbf49e6b14ad3a2f4db38f9
source_name: ''
source_type: 4
source_version: ''
start_time: 1607022449803
status: 4
tags: []
user_id: jovyan
