steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/ai-vqc/kubeflow-pipeline:latest', './pipeline']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/kubeflow-pipeline', 'kubeflow-pipeline=eu.gcr.io/ai-vqc/kubeflow-pipeline:latest']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-d'
    - 'CLOUDSDK_CONTAINER_CLUSTER=kubeflow-generali'