artifact_uri: /tmp/mlflowruns/0/dc9c4b0393e94ac8a0b70e0bc409b408/artifacts
end_time: 1607022242228
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: dc9c4b0393e94ac8a0b70e0bc409b408
run_uuid: dc9c4b0393e94ac8a0b70e0bc409b408
source_name: ''
source_type: 4
source_version: ''
start_time: 1607022241865
status: 3
tags: []
user_id: jovyan
