artifact_uri: /tmp/mlflowruns/0/19e54dee7f064abb86caca53feb658f3/artifacts
end_time: 1607019437846
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 19e54dee7f064abb86caca53feb658f3
run_uuid: 19e54dee7f064abb86caca53feb658f3
source_name: ''
source_type: 4
source_version: ''
start_time: 1607019437223
status: 4
tags: []
user_id: jovyan
