version: '3'

services:

  backend:
    build: ./flask/.
    restart: always
    volumes:
      - ./flask/uploaded_photos:/uploaded_photos
      - ./flask/model:/model
    command: ["gunicorn", "-w", "3", "-b", ":5000", "-t", "360", "--reload", "api.wsgi:app"]
    networks:
      - apinetwork
    expose:
      - "5000"
    ports:
      - "5000:5000"

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./flask:/usr/share/nginx/html
    networks:
      - apinetwork
    expose:
      - "80"
    ports:
      - "8080:80"
    depends_on:
      - backend
  
networks:
  apinetwork: