artifact_uri: s3://mlflowruns/4/ab4df0e3a0bc4ea88c762449549f952a/artifacts
end_time: 1607023153324
entry_point_name: ''
experiment_id: '4'
lifecycle_stage: active
name: ''
run_id: ab4df0e3a0bc4ea88c762449549f952a
run_uuid: ab4df0e3a0bc4ea88c762449549f952a
source_name: ''
source_type: 4
source_version: ''
start_time: 1607023153115
status: 4
tags: []
user_id: jovyan
