artifact_uri: /tmp/mlflowruns/0/01eba763f8764bd18b3c135de41fbf32/artifacts
end_time: 1607019576925
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 01eba763f8764bd18b3c135de41fbf32
run_uuid: 01eba763f8764bd18b3c135de41fbf32
source_name: ''
source_type: 4
source_version: ''
start_time: 1607019576260
status: 3
tags: []
user_id: jovyan
