artifact_uri: s3://mlflowruns/5/e904b1ed02a14a0b86a1ae628d2c9aad/artifacts
end_time: 1607023295300
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: e904b1ed02a14a0b86a1ae628d2c9aad
run_uuid: e904b1ed02a14a0b86a1ae628d2c9aad
source_name: ''
source_type: 4
source_version: ''
start_time: 1607023288057
status: 4
tags: []
user_id: jovyan
