artifact_uri: /tmp/mlflowruns/0/33be0a918de64a3085a1c182ce4da86a/artifacts
end_time: 1607019414440
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 33be0a918de64a3085a1c182ce4da86a
run_uuid: 33be0a918de64a3085a1c182ce4da86a
source_name: ''
source_type: 4
source_version: ''
start_time: 1607019414218
status: 4
tags: []
user_id: jovyan
