artifact_uri: /tmp/mlflowruns/0/c3fd2ee016eb4a3bb789124094a65c98/artifacts
end_time: 1607019331940
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: c3fd2ee016eb4a3bb789124094a65c98
run_uuid: c3fd2ee016eb4a3bb789124094a65c98
source_name: ''
source_type: 4
source_version: ''
start_time: 1607019331516
status: 3
tags: []
user_id: jovyan
