version: '3'

services:

  mlflowui:
    build: ./mlflowUI/.
    restart: always
    volumes: ['./storage/mlflow:/tmp/mlflowruns'] 
    networks:
        - jupyter
    expose:
        - "5000"
    ports:
        - "5000:5000"
    environment: 
      - LC_ALL=C.UTF-8 
      - LANG=C.UTF-8
      - MLFLOW_S3_ENDPOINT_URL=http://ai_toolkit_elyra_minio_1:9000
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123

  elyra:
    image: elyra/elyra:dev
    restart: always
    command: ["jupyter", "lab", "--debug"]
    volumes: ['./storage/jupyter:/home/jovyan/work']
    networks:
      - jupyter
    expose:
      - "8888" 
    ports:
      - "8888:8888"
    #privileged: true
    environment: 
      - MLFLOW_S3_ENDPOINT_URL=http://ai_toolkit_elyra_minio_1:9000
  
  minio:
    image: minio/minio
    restart: always
    command: ["server", "/export"]
    volumes: ['./storage/minio:/export']
    networks:
      - jupyter
    expose:
      - "9000"
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  jupyter: