name: Train

docker_env:
   image:  rio05docker/obj_detection_cd:rpi3_mlflow_${GITHUB_SHA}

entry_points:
  main:
    parameters:
      data_file: path
      regularization: {type: float, default: 0.1}
    command: "python main.py"

  #validate:
  #  parameters:
  #    data_file: path
  #  command: "python validate.py {data_file}"