artifact_uri: s3://mlflowruns/4/4d3a3d6f0d0f41c78d8bd6437b02ef25/artifacts
end_time: 1607023102422
entry_point_name: ''
experiment_id: '4'
lifecycle_stage: active
name: ''
run_id: 4d3a3d6f0d0f41c78d8bd6437b02ef25
run_uuid: 4d3a3d6f0d0f41c78d8bd6437b02ef25
source_name: ''
source_type: 4
source_version: ''
start_time: 1607023102032
status: 4
tags: []
user_id: jovyan
