name: obj_detection_cd

on:
  push: # Trigger when push on develop branch
   branches:
      - develop
        
jobs:
  buildx:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
        with:
          ref: develop
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1.0.4
        with:
          version: latest
      
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
        
      - 
        name: Login to GitHub Docker Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      #Build&Push -custom model trainer
      -
        name: Build and push custom train ARM container #see: https://github.com/marketplace/actions/docker-buildx
        run: |
          docker buildx build \
            --tag rio05docker/obj_detection_cd:rpi3_mlflow_custom \
            --platform linux/arm/v7 \
            --output "type=image,push=true" \
            --file ./batch_custom_model/Dockerfile \
            ./batch_custom_model/
        
      -
        name: Build and push batch image recognition transfer learning retrain container #see: https://github.com/marketplace/actions/docker-buildx
        run: |
          docker buildx build \
            --tag rio05docker/tf2_transfer_learning:${GITHUB_SHA} \
            --platform linux \
            --output "type=image,push=true" \
            --file ./batch_edge_tpu_image_classification/image_classification_transfer_learning_tf2/Dockerfile \
            ./batch_edge_tpu_image_classification/image_classification_transfer_learning_tf2/
      
      #Build&Push - batch masked rcnn model trainer
      #-
      #  name: Build and push batch masked rcnn model trainer #see: https://github.com/marketplace/actions/docker-buildx
      #  run: |
      #    docker buildx build \
      #      --tag rio05docker/obj_detection_cd:rpi3_mrcnn_${GITHUB_SHA} \
      #      --platform linux/arm/v7 \
      #      --output "type=image,push=true" \
      #      --file ./batch_masked_rcnn/Dockerfile \
      #      ./batch_masked_rcnn/
      
